// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGcAND_SR1f_qm7FCR61ySl_2zD79H20',
    appId: '1:242782129968:web:ab4b464b1aa13dd97f02f5',
    messagingSenderId: '242782129968',
    projectId: 'biblioteca1-ed708',
    authDomain: 'biblioteca1-ed708.firebaseapp.com',
    storageBucket: 'biblioteca1-ed708.firebasestorage.app',
    measurementId: 'G-YEKYZVSQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUhI6bPyUwGlMAPkd1CjOlq1nObmg1Oo',
    appId: '1:242782129968:android:55c0b2d35714db0f7f02f5',
    messagingSenderId: '242782129968',
    projectId: 'biblioteca1-ed708',
    storageBucket: 'biblioteca1-ed708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMzAIM3tJuftZRLD6Yjq47oqNSZoAVdvw',
    appId: '1:242782129968:ios:be2636fb28587f487f02f5',
    messagingSenderId: '242782129968',
    projectId: 'biblioteca1-ed708',
    storageBucket: 'biblioteca1-ed708.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca1',
  );

}